from pathlib import Path

DAY_ORDER = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
]

PACKAGE_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = PACKAGE_ROOT.parent.parent
PIPELINES_OUTPUT_DIR = PROJECT_ROOT / "pipelines" / "output"
DEFAULT_OUTPUT_DIR = PACKAGE_ROOT / "output"

MIN_DELIVERY_SHARE = 0.005
MAX_DELIVERY_SHARE = 0.20
HIGH_CONFIDENCE_SHARE_SPREAD = 0.20
MEDIUM_CONFIDENCE_SHARE_SPREAD = 0.35
LOW_CONFIDENCE_SHARE_SPREAD = 0.50
MIN_PRODUCTIVITY_TARGET = 0.25
TARGET_FALLBACK_SHIFT = "all_day"
LOW_CONFIDENCE_SALES_UPLIFT_CAP = 3.5
LOW_CONFIDENCE_MIN_TARGET_SLOTS = 8
LOW_CONFIDENCE_TARGET_CAP_MULTIPLE = 1.5
MIN_SHAPE_SUPPORT_ROWS = 12
MAX_SPARSE_SHAPE_TO_UNIFORM_RATIO = 4.0
